#!/bin/bash
set -u -e -C;
shopt -s nullglob;

function err { echo $'\e[1;31m'"$@"$'\e[m' >&2; exit 1; }
function warn { echo $'\e[1;35m'"$@"$'\e[m' >&2; }
function info { echo $'\e[36m'"$@"$'\e[m'; }

function ask_yN {
    local answer='';
    read -n 1 -s -p $'\e[34m'"$* [yN]"$'\e[m' answer;
    if test "${answer}" = y; then
        info yes;
        return 0;
    fi;
    info no;
    return 1;
}

id="$(pactl load-module module-loopback latency_msec=$((1000 * ${1?Latency in seconds})))";
trap "pactl unload-module '${id}'" EXIT

echo  $'\e[34mHit q to quit\e[m'
until read -n1 -s answer; test "$answer" = q; do :;done
