#!/usr/bin/python

import sys
import os
import re



badChars = re.compile('[ \x1b\[\]!?*<>&\n\t"\'$\\#:;|()]')



# Quoting for printing the old name
def quote(x):
    return x.replace('\t', '\\t').replace('\n', '\\n').replace("'","'\\''")



def main(args):

    with open('detox.log', 'a') as log:
        for p in os.scandir():

            # Calculate new name by splitting at bad characters, removing
            # empty words, and then join with interspesing `_`.
            sanitized = "_".join(
                filter(lambda l: l, badChars.split(p.name))
            )

            # If there is a better name, try to rename.
            if p.name != sanitized:

                q = quote(p.name)

                # make sure traget does not exist, before moving
                try:
                    if p.is_dir():
                        os.mkdir(sanitized, mode = 0o100)
                    else:
                        with open(sanitized, "x") as f:
                            pass
                except FileExistsError:
                    print(
                        f"Exists: {sanitized}, not renaming: {q}"
                    )
                    return

                # try to rename, automatically overwriting dummy created above
                try:
                    os.rename(p, sanitized)
                    print(f"Renamed \x1b[35m{q}\x1b[m to \x1b[34m{sanitized}\x1b[m")
                    print(f"mv '{sanitized}' '{q}'", file = log)
                except OSError as e:
                    print(e)

                    # cleanup, remove dummy created above
                    try:
                        if p.is_dir():
                            os.rmdir(sanitized)
                        else:
                            os.remove(sanitized)
                    except OSError as e:
                        print(e)

    return 0



if __name__ == '__main__':
    try:
        exit(main(sys.argv[1:]))
    except KeyboardInterrupt:
        print('KeyboardInterrupt')
        exit(1)



# [1]: https://stackoverflow.com/questions/38307995/create-os-direntry
