#!/bin/bash
set -u -e -C;
shopt -s nullglob;

function err { echo $'\e[1;31m'"$@"$'\e[m' >&2; exit 1; }
function warn { echo $'\e[31m'"$@"$'\e[m' >&2; }
function info { echo $'\e[34m'"$@"$'\e[m'; }

function ask_yN {
    local answer='';
    read -n 1 -s -p $'\e[34m'"$* [yN]"$'\e[m' answer;
    if test "${answer}" = y; then
        info yes;
        return 0;
    fi;
    info no;
    return 1;
}

for i in "$@"; do
    grep -Fq "$i" .gitignore && continue;
    if ! test -e "$i"; then
        ask_yN "Add non-existing ${i}?" || continue;
    fi;
    echo "$i" >> .gitignore;
done;
test -e .gitignore && git add .gitignore;
