#!/bin/bash
# Copyright 2019 Stefan Klinger <http://stefan-klinger.de>
set -u -e -C;
shopt -s nullglob;

function err { echo $'\e[1;31m'"$@"$'\e[m' >&2; exit 1; }
function warn { echo $'\e[31m'"$@"$'\e[m' >&2; }
function info { echo $'\e[34m'"$@"$'\e[m'; }

for i in "$@"; do
    if ! [[ "$i" =~ / ]]; then i="/${i}"; fi
    if ! test -e "./${i}"; then warn "Does not exist: $i"; continue; fi
    if grep -Fsq "$i" .gitignore; then continue; fi
    echo "$i" >> .gitignore;
done;
if test -e .gitignore; then
    git add .gitignore
    git --no-pager diff HEAD -- .gitignore
fi
