#!/bin/bash
# Copyright 2023 Stefan Klinger <http://stefan-klinger.de>
set -u -e -C
shopt -s nullglob

# This requires a JavaScript interpreter `js`.  ArchLinux packages
# `jsXYZ` with package names containing the version number.  Find
# the latest one, install and fix with `# ln -s /usr/bin/jsXYZ
# /usr/local/bin/js`.

ip -j addr | js <(cat <<'.'
Array.prototype.flat = function() { return [].concat(...this); }
txt=''; while (l = readline()) txt += l
rs = JSON.parse(txt).map(x => x.addr_info).flat().map(x => [x.scope, x.local])
if (typeof rs == 'undefined') { printErr("nothing found"); quit(1) }
//print(JSON.stringify(rs))
for (var i = 0; i < rs.length; i++) print(rs[i].join('\t'))
.
)
