#!/bin/bash
# Copyright 2019 Stefan Klinger <http://stefan-klinger.de>
set -u -e -C;
shopt -s nullglob;

img="${HOME}/.lockscreen.png"

if ! test -r "${img}"; then
    echo "Not found: ${img}"
    echo 'Creating new lockscreen image from screenshot'

    imlib2_grab "${img}"
    gmic \
        input "$img" \
        wave 10,0.01 blur 7,0 input 1,1,1,3 blend darken,10% \
        output "$img"
fi

i3lock -f -e -n -i "${HOME}/.lockscreen.png"
