#!/bin/bash
set -u;

# This needs `less` to fail when `r` is hit.  To set this up, do
#
#     $ lesskey - <<<'r quit 1'

opt=();

while test "${1:0:1}" = '-'; do
    opt+=("${1}");
    shift;
done;

until "$@" | less -S "${opt[@]}"; do :; done
