#!/bin/bash
# Copyright 2019 Stefan Klinger <http://stefan-klinger.de>
set -u -e -C
shopt -s nullglob

img="$(mktemp -t screenshot.$(date +%Y%m%d-%H%M%S).XXXX.png)"
echo "Writing screenshot to: $img"

imlib2_grab "$img"
#geeqie "$img"
gimp "$img"
