#!/bin/bash
set -u -e -C;
shopt -s nullglob;

function err { echo $'\e[1;31m'"$@"$'\e[m' >&2; exit 1; }
function warn { echo $'\e[1;35m'"$@"$'\e[m' >&2; }
function info { echo $'\e[36m'"$@"$'\e[m'; }

function ask_yN {
    local answer='';
    read -n 1 -s -p $'\e[34m'"$* [yN]"$'\e[m' answer;
    if test "${answer}" = y; then
        info yes;
        return 0;
    fi;
    info no;
    return 1;
}

name="${1%.7z}"

tmp="$(mktemp -d "${name}.XXXXXXXX")"
info "Temporary location: ${tmp}"

7z x -o"${tmp}" "${1}" || err "7z failed"

test -e "${name}" && err "Already exists: ${name}"
if test "$(ls -A "${tmp}")" = "${name}"; then
    mv "${tmp}/${name}" "${name}"
    rmdir "${tmp}"
else
    xs=("${tmp}"/*)
    if test "${#xs[@]}" -eq 1; then
        warn "Renaming top-level element: ${xs[0]}"
        mv "${xs[0]}" "${name}"
        rmdir "${tmp}"
    else
        warn "Created new top-level directory"
        mv "${tmp}" "${name}"
    fi;
fi;
